/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.AutorDB;
import db.EdituraDB;
import db.FurnizorDB;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import service.MainController;

/**
 *
 * @author Ionut
 */
public class AdaugareCarteFrame extends javax.swing.JFrame {
    DefaultListModel<AutorDB> model1 = new DefaultListModel<AutorDB>();
    DefaultListModel<EdituraDB> model2 = new DefaultListModel<>();
    DefaultListModel<FurnizorDB> model3 = new DefaultListModel<>();
    DefaultListModel<AutorDB> model4 = new DefaultListModel<>();
    ArrayList<AutorDB> autoric = new ArrayList<>();
    EdituraDB editurac;
    FurnizorDB furnizorc;
    CartiFrame cf;

    /**
     * Creates new form AdaugareCarteFrame
     */
    public AdaugareCarteFrame(CartiFrame cf) {
        initComponents();
        this.cf = cf;
        jList1.setModel(model1);
        jList2.setModel(model2);
        jList3.setModel(model3);
        jList4.setModel(model4);
        afisareEdituri();
        afisareFurnizori();
        afisareAutori();
        setTitle("Adaugare carte");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void afisareEdituri(){
        model2.clear();
        List<EdituraDB> edituri = MainController.getInstance().getEdituri();
        for(EdituraDB e: edituri){
            model2.addElement(e);
        }
    }
    
    public void afisareFurnizori(){
        model3.clear();
        List<FurnizorDB> furnizori = MainController.getInstance().getFurnizori();
        for(FurnizorDB f: furnizori){
            model3.addElement(f);
        }
    }
    
    public void afisareAutori(){
        int ok=1;
        model4.clear();
        List<AutorDB> autori = MainController.getInstance().getAutori();
        for(AutorDB a: autori){
            ok = 1;
            for(AutorDB ac: autoric){
                if(a.getId()==ac.getId()){
                    ok=0; 
                }     
            }
            if(ok==1) model4.addElement(a);
        }
    }
    
    public void afisareAutoriC(){
        model1.clear();
        for(AutorDB ac: autoric){
            model1.addElement(ac);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("TITLU:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("ISBN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel3.setText("STOC:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        jLabel4.setText("EDITURA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        jLabel5.setText("FURNIZOR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 11, 218, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, 218, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 71, 220, -1));

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 109, 220, -1));

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 147, 220, -1));

        jButton2.setText("ADAUGA CARTE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 371, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 223, 220, -1));

        jLabel6.setText("PRET:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 185, 220, -1));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 190, -1));

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, -1));

        jLabel7.setText("EDITURI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel8.setText("FURNIZORI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 45, 145, 308));

        jLabel9.setText("AUTORI:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 236, -1, -1));

        jLabel10.setText("AUTORI");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 25, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\Anul 3\\BD\\Proiect\\mare_carti-mare.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String titlu = jTextField1.getText();
        String isbn = jTextField2.getText();
        int stoc = Integer.parseInt(jTextField3.getText());
        editurac = (EdituraDB)jList2.getSelectedValue();
        furnizorc = (FurnizorDB)jList3.getSelectedValue();
        double pret = Double.parseDouble(jTextField6.getText());
        
        
        boolean rez = MainController.getInstance().adaugaCarte(titlu, isbn, stoc, pret, editurac, furnizorc, autoric);
        if(rez==true){
            JOptionPane.showMessageDialog(null, "Cartea a fost adaugata!");
            cf.afisareCarti();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "O carte cu acelasi ISBN exista deja!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList4MouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1 &&
                evt.getClickCount() == 2 &&
                jList4.getSelectedIndex() > -1){
            autoric.add((AutorDB)jList4.getSelectedValue());
            afisareAutoriC();
            afisareAutori();
        }
    }//GEN-LAST:event_jList4MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1 &&
                evt.getClickCount() == 2 &&
                jList2.getSelectedIndex() > -1){
            editurac = (EdituraDB)jList2.getSelectedValue();
            jTextField4.setText(editurac.getNume());
            
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1 &&
                evt.getClickCount() == 2 &&
                jList3.getSelectedIndex() > -1){
            furnizorc = (FurnizorDB)jList3.getSelectedValue();
            jTextField5.setText(furnizorc.getNume());   
        }
    }//GEN-LAST:event_jList3MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
